SELECT ENAME 
FROM EMP 
WHERE SAL > (
    SELECT SAL 
    FROM EMP 
    WHERE ENAME = 'ADAMS'
);


SELECT ENAME, SAL 
FROM EMP 
WHERE SAL < (SELECT SAL FROM EMP WHERE ENAME = 'KING');

SELECT ENAME, DEPTNO
FROM EMP
WHERE DEPTNO = (SELECT DEPTNO FROM EMP WHERE ENAME='JONES');

SELECT ENAME, JOB
FROM EMP
WHERE JOB = (SELECT JOB FROM EMP WHERE ENAME ='JAMES');

SELECT ENAME, HIREDATE
FROM EMP
WHERE HIREDATE = (SELECT HIREDATE FROM EMP WHERE ENAME='SCOTT');

SELECT ENAME, HIREDATE
FROM EMP
WHERE HIREDATE > (SELECT HIREDATE FROM EMP WHERE job='PRESIDENT');

SELECT ENAME, SAL
FROM emp
WHERE SAL < (SELECT SAL FROM EMP WHERE EMPNO =7839);

SELECT ENAME,hiredate 
FROM emp
WHERE HIREDATE<(SELECT HIREDATE FROM EMP WHERE ENAME='MILLER');

SELECT ENAME,EMPNO
FROM emp
WHERE SAL > all(SELECT SAL FROM EMP WHERE ENAME = 'ALLEN');

SELECT ENAME, SAL
FROM emp
WHERE SAL > (SELECT MAX(SAL) FROM emp WHERE ENAME = 'MILLER')
  AND SAL < (SELECT MIN(SAL) FROM emp WHERE ENAME = 'ALLEN');

SELECT *
FROM emp
WHERE DEPTNO = 20
  AND JOB IN (SELECT JOB FROM emp WHERE ENAME = 'SMITH');
 
 SELECT *
FROM emp
WHERE DEPTNO = 20
  AND JOB IN (SELECT JOB FROM emp WHERE ENAME = 'SMITH');

  SELECT * FROM emp WHERE  job = 'MANAGER'
  AND DEPTNO in (SELECT DEPTNO FROM EMP WHERE ENAME= 'TURNER');
  
  SELECT ENAME, HIREDATE
FROM emp
WHERE HIREDATE > '1980-12-31'
  AND HIREDATE < (SELECT MIN(HIREDATE) FROM emp WHERE ENAME = 'KING');

SELECT ENAME, SAL, (SAL * 12) AS ANNUAL_SAL
FROM emp
WHERE SAL < (SELECT MIN(SAL) FROM emp WHERE ENAME = 'BLAKE')
  AND SAL > 3500;

SELECT *
FROM EMP
WHERE SAL > (SELECT MAX(SAL) FROM emp WHERE ENAME = 'SCOTT')
  AND SAL < (SELECT MIN(SAL) FROM emp WHERE ENAME = 'KING');
  
SELECT ENAME
FROM emp
WHERE ENAME LIKE 'A%'
AND DEPTNO IN (SELECT DEPTNO FROM EMP WHERE ENAME='BLAKE');

SELECT*
FROM emp
WHERE JOB='CLERK'
AND DEPTNO IN (SELECT DEPTNO FROM EMP WHERE ENAME='TURNER');

SELECT ENAME, SAL, JOB
FROM emp
WHERE (SAL * 12) > (SELECT MAX(SAL * 12) FROM emp WHERE ENAME = 'SMITH')
  AND (SAL * 12) < (SELECT MIN(SAL * 12) FROM emp WHERE ENAME = 'KING');


