SELECT*FROM emp;
SHOW TABLES;
USE emp;
SELECT E.ENAME, D.LOC FROM EMP E
INNER JOIN DEPT D
ON E.DEPTNO = D.DEPTNO;

SELECT E.ENAME, D.DNAME FROM EMP E
INNER JOIN DEPT D
ON E.DEPTNO = D.DEPTNO
WHERE D.DNAME LIKE '%A%';

SELECT D.DNAME, E.SAL * 12 AS ANNUAL_SALARY FROM EMP E
INNER JOIN DEPT D
ON E.DEPTNO = D.DEPTNO
WHERE E.SAL > 2340;

SELECT D.DNAME, E.SAL
FROM EMP E
INNER JOIN DEPT D
ON E.DEPTNO = D.DEPTNO
WHERE D.DNAME = 'ACCOUNTING';

SELECT E.ENAME ,D.DNAME FROM EMP E
INNER JOIN  DEPT D
ON E.DEPTNO = D.DEPTNO
WHERE E.JOB = 'SALESMAN';
SELECT D.DNAME , JOB FROM EMP E
INNER JOIN  DEPT D
ON E.DEPTNO = D.DEPTNO 
WHERE E.JOB LIKE '%S%' AND D.DNAME LIKE '%S%';
SELECT D.DNAME ,MGR FROM EMP E
INNER JOIN  DEPT D
ON E.DEPTNO = D.DEPTNO
WHERE MGR = '7839';

SELECT D.DNAME, E.HIREDATE FROM EMP E
INNER JOIN  DEPT D
ON E.DEPTNO = D.DEPTNO
WHERE E.HIREDATE < '1983-12-31' AND D.DNAME IN ('ACCOUNTING', 'RESEARCH');

SELECT E.ENAME ,D.DNAME FROM EMP E
INNER JOIN  DEPT D
ON E.DEPTNO = D.DEPTNO
WHERE COMM IS NOT NULL AND E.DEPTNO IN (10,30);

SELECT E.ENAME, D.DNAME 
FROM EMP E 
INNER JOIN DEPT D ON E.DEPTNO = D.DEPTNO 
WHERE D.LOC = 'NEW YORK' 
  AND E.EMPNO IN (7839, 7902);


